### ISSUE TITLE
La pantalla se queda en negro cuando se ejecuta en una maquina con MIPSEL

### ISSUE THREAD

**Issue by willicab** [milmazz/pygame-salud#8]
Al principio salía además el mensaje:

```
open /dev/sequencer or /dev/snd/seq: no such file or directory
```

Ejecuté el siguiente comando

```
modprobe snd-seq
```

Ya no sale el mensaje pero sigue quedando la pantalla negra

**Comment by milmazz** [comment]
Por favor indicar _Sistema Operativo_ utilizado y su versión, además de la configuración pertinente para el defecto indicado.

¿Ya verificaste que cumples con los requisitos del juego?, es decir, tener instalado los paquetes: 
- python-pygame (>= 1.7.1)
- ttf-dejavu-core (>= 2.25),

**Comment by willicab** [comment]
si, tiene instalado ttf-dejavu-core-2.25-3 y y python-pygame-1.7.1release-4.2
